### ISSUE TITLE
Missing package dependency?

### ISSUE THREAD

**Issue by jwokaty** [Bioconductor/chipseq#3]
See https://bioconductor.org/checkResults/3.17/testing-LATEST/chipseq/nebbiolo2-checksrc.html. Not clear if missing a package or another problem.

**Comment by hpages** [comment]
They seem to use **BSgenome.Mmusculus.UCSC.mm9** in their examples. Do they declare it?

**Comment by Oluwabukolab** [comment]
> See https://bioconductor.org/checkResults/3.17/testing-LATEST/chipseq/nebbiolo2-checksrc.html. Not clear if missing a package or another problem.

Hi @jwokaty So I try running the source code and ran into the same error. Then i try installing the missing package "BSgenome.Mmusculus.UCSC.mm9" but keeping saying It is not available for this version of R and this is the only version of R available. Please advise 

![Screenshot (36)](https://user-images.githubusercontent.com/112485492/228584100-1e4c00a8-2970-409c-828f-e745d98ce4b3.png)

**Comment by jwokaty** [comment]
@Bukolab99 I'm sorry I missed this. Try installing with `BiocManager::install("BSgenome.Mmusculus.UCSC.mm9")`. `BiocManager` is the preferred tool for installing Bioconductor packages. If you have questions about this further, please text on the sweave2rmd channel since this issue is about another problem.

**Comment by hpages** [comment]
Note that there's still the issue that **chipseq** doesn't declare **BSgenome.Mmusculus.UCSC.mm9**, which is now something that triggers an error on the daily builds: https://bioconductor.org/checkResults/devel/bioc-LATEST/chipseq/

**Comment by lshep** [comment]
https://github.com/Bioconductor/chipseq/commit/90652b8e50a2f24c55b6a8b28aa6c5d220f93f51
